/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103x6.h"
#include "gpio_driver.h"
#include "lcd.h"
#include "keypad.h"
#include "exti_driver.h"


unsigned int IRQ_FALG = 0;
int VAL1 = 3;
int VAL2 = 7;
int VAL3 = 0;
int CR = 9;
int IPSRS = 0;

void my_delay(int x)
{
	uint32_t i,j;
	for(i=0; i<x ; i++)
	{
		for(j=0; j<255; j++);
	}
}

void EXTI9PB9_CALLBACK(){
	IRQ_FALG = 1;
	/************LAB6*******************/
	__asm("nop \t\n nop \t\n nop");

	__asm("MRS %0, IPSR"
			:"=r" (IPSRS));

	__asm("nop \t\n nop \t\n nop");

	/*******************************************************/
}


int main(void)
{

	//Enable the clocks
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	LCD_INIT();
	LCD_clear_screen();

	EXTI_PinCnfig_t EXTI_CFG ;
	EXTI_CFG.EXTI_PIN = EXTI9_PB9;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_Rising;
	EXTI_CFG.Ptr_IRQ_CALLBACK = EXTI9PB9_CALLBACK ;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_ENABLE;

	MCAL_EXTI_GPIO_INIT(&EXTI_CFG);

	IRQ_FALG = 1;

	__asm("nop \t\n nop \t\n nop");


/****************LAB2: VAL as input*********************/
	//mov VAL, 0xff (VAL = 0)
//	__asm("mov %0, #0xff"
//			:"=r" (VAL) );
/*******************************************************/

/****************LAB3: VAL as input*********************/
	//mov R0, VAL (VAL = 3)
	//__asm("mov R0,%0"
	//		:
	//		: "r"  (VAL) ); // Input operand: "r" = use a register for VAL
/*******************************************************/
/************LAB4: VAL3 = VAL1 + VAL2*******************/
//	__asm("add %0,%1,%2" // %0 = %1 + %2 (VAL3 = VAL1 + VAL2) %0 allocates register for output v3...
//			:"=r" (VAL3) // Output: VAL3 (write-only)
//			:"r" (VAL1), /// Inputs: VAL1 and VAL2
//			"r" (VAL2)); //r :The compiler loads the value of the C s (VAL1, VAL2) into a register
						 //=r :The value in this register is stored into the C variable ( VAL3).
	/***or****/
/*	__asm("add %[out0],%[in0],%[in1]"
			:[out0] "=r" (VAL3)
			:[in0] "r" (VAL1),
			:[in1] "r" (VAL2));
*/
/*******************************************************/
/************LAB6*******************/
	__asm("MRS %0, CONTROL" // We will read the control reg into output operand %0
			:"=r" (CR));//output operand

/*******************************************************/

	__asm("nop \t\n nop \t\n nop");

	while(1)
	{
		if (IRQ_FALG)
		{
			LCD_clear_screen();
			IRQ_FALG = 0;
		}
	}

}

