/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>



// GPIO
#define GPIOPA_Base 0x40010800
#define RCC_base 0x40021000
#define GPIO_CRH   *((volatile uint32_t*)(GPIOPA_Base + 0x04))//ptr to volatile unsigned 32 bit integer that points to the mentioned adress
#define GPIO_CRL   *((volatile uint32_t*)(GPIOPA_Base + 0x00))
#define GPIOPA_ODR  *((volatile uint32_t*)(GPIOPA_Base + 0x0C))//ptr to volatile unsigned 32 bit integer that points to the mentioned adress
#define RCC_APB2ENR  *((volatile uint32_t*)(RCC_base + 0x18))
//EXTI
#define EXTI_Base  0x40010400
#define EXTI_IMR *((volatile uint32_t*)(EXTI_Base + 0x00))
#define EXTI_RTSR *((volatile uint32_t*)(EXTI_Base + 0x08))
#define EXTI_PR *((volatile uint32_t*)(EXTI_Base + 0x14))

//AFIO
#define AFIO_Base  0x40010000
#define AFIO_EXTICR1 *((volatile uint32_t*)(AFIO_Base + 0x08))

#define NVIC_EXTIEN0 *((volatile uint32_t*)(0xE000E100))

void clock_init(){
// init clock  for GPIO PORT A :
	//	Bit 2 IOPARST: I/O port A reset
	//	 Set and cleared by software.
	//	 0: No effect
	//	 1: Reset I/O port A
	RCC_APB2ENR |= (1<<2);

	//ENABLE BIT0 AFION: ALTERNATIVE INPIUT OUTPUT ENABLE
	RCC_APB2ENR |= (1<<0);

	//
}

void GPIO_inti(){
	//pin 13 port A
	GPIO_CRH &=0Xff0fffff; // Clear configuration bits for pin 13
	GPIO_CRH |=0X00200000; // Set pin 13 as output (mode = 2, CNF = 0)
	//PIN A0: FLOATING POINT(RESET STATE)
	GPIO_CRL |= (1<<2);

}
int main(void)
{

	clock_init();
	GPIO_inti();
	//EXTI0 configuration to port A0
	AFIO_EXTICR1=0;


	//Enable rising trigger
	EXTI_RTSR |= (1<<0);

	//Enable EXTI line 0
	EXTI_IMR |= (1<<0);

	//ENABLE INTERRUPT OF NVIC IRQ6 >> EXTI0
	NVIC_EXTIEN0 |= (1<<6);
	while(1);

}
void EXTI0_IRQHandler(void){
	//toggle led pin A 13
	GPIOPA_ODR ^= (1<<13); //set bit 13

	//clear pending request register
	EXTI_PR |= (1<<0);

}
