/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



	#if !defined(__SOFT_FP__) && defined(__ARM_FP)
 	 #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
	#endif

#include <stdint.h>
#define MCU_ACT_AS_MASTER
//#define MCU_ACT_AS_SLAVE
#include "STM32F103x6.h"
#include "gpio_driver.h"
#include "lcd.h"
#include "keypad.h"
#include "exti_driver.h"
#include "usart_driver.h"
#include "spi_driver.h"

uint16_t unko;

void SPI1_IRQ_CALLBACK (struct S_IRQ_SRC irq_src)
{
#ifdef MCU_ACT_AS_SLAVE
	if(irq_src.RXNE)
	{

		MCAL_SPI_RECIEVE_DATA(SPI1, &unko, Polling_DISABLE);
		MCAL_UART_SEND_DATA(USART1, &unko, enable);
	}
#endif
}

void OUSS_UART_IRQ_CALLBACK(void)
{
#ifdef MCU_ACT_AS_MASTER
	MCAL_UART_RECIEVE_DATA(USART1, &unko, disable); //Receive data from UART1 and store it in 'unko'
	MCAL_UART_SEND_DATA(USART1, &unko, enable);  // Send the received data back to UART1
	//SEND TO SPI
	MCAL_GPIO_Write_PIN(GPIOA, GPIO_PIN_4, 0);
	MCAL_SPI_TX_RX(SPI1, &unko, Polling_EN);
	MCAL_GPIO_Write_PIN(GPIOA, GPIO_PIN_4, 1);
	#endif
}

int main(void)
{


	//Enable the clocks
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
//********/UART INTIALAZTION/********//
	UART_Config UartOUScfg;
	UartOUScfg.BaudeRate = UART_BAUDRATE_115200;
	UartOUScfg.HW_Flow_ctrl = UART_HW_FLOW_CTRL_NONE;
	UartOUScfg.IRQ_Enable = UART_IRQ_ENABLE_RXNEIE;

	UartOUScfg.P_IRQ_CALLBACK = OUSS_UART_IRQ_CALLBACK;

	UartOUScfg.Parity = UART_Parity_NONE;
	UartOUScfg.Payload_Length = UART_PAYLOAD_LENGTH_8B;
	UartOUScfg.Stopbits = UART_StopBits_1;
	UartOUScfg.USART_MODE = UART_MODE_TX_RX;

	MCAL_UART_INIT(USART1, &UartOUScfg);
	MCAL_UART_GPIO_SET_PINS(USART1);

//********/spi INTIALAZTION/********//
	SPI_CONFIG SPI1CFG;
	GPIO_PinConfig_t PinCfg;

#ifdef MCU_ACT_AS_MASTER

	SPI1CFG.Device_Mode = SPI_Devide_Mode_Master;
	SPI1CFG.IRQ_ENABLE = SPI_IRQ_Enable_NONE;
	SPI1CFG.NSS = SPI_NSS_SW_Slave_SET;
	SPI1CFG.P_IRQ_CallBack = NULL;

	//CONFIGURE SS ON PORT A4 BY GPIO
	PinCfg.GPIO_PinNumber = GPIO_PIN_4;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10MHZ;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	//Force the slave select (high) idle mode
	MCAL_GPIO_Write_PIN(GPIOA, GPIO_PIN_4, 1);

#endif
#ifdef MCU_ACT_AS_SLAVE

	SPI1CFG.Device_Mode = SPI_Devide_Mode_Slave;
	SPI1CFG.IRQ_ENABLE = SPI_IRQ_Enable_RXNEIE;
	SPI1CFG.NSS = SPI_NSS_HW_Slave;
	SPI1CFG.P_IRQ_CallBack = SPI1_IRQ_CALLBACK;

#endif

	//coumon configuration
	SPI1CFG.CLK_Phase = SPI_CLK_Phase_2Edge_data_capture;
	SPI1CFG.CLK_Polarity = SPI_CLK_Polarity_High_Idle;
	SPI1CFG.Data_Size = SPI_DataSize_8bit;
	SPI1CFG.Frame_Format = SPI_Frame_Format_MSB_Transmitted_first;
	//assume by default pclk2 = 8mhz
	SPI1CFG.SPI_BR_Prescaler = SPI_SPI_BR_Prescaler_8;
	SPI1CFG.Communication_Mode = SPI_Direction_2lines;
	MCAL_SPI_INIT(SPI1, &SPI1CFG);
	MCAL_SPI_GPIO_SET_PINS(SPI1);


	while(1)
	{

	}


}

