/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>



// Register addresses
#define GPIOPA_Base 0x40010800
#define RCC_base 0x40021000
#define GPIO_CRH   *((volatile uint32_t*)(GPIOPA_Base + 0x04))//ptr to volatile unsigned 32 bit integer that points to the mentioned adress
#define GPIOPA_ODR  *((volatile uint32_t*)(GPIOPA_Base + 0x0C))//ptr to volatile unsigned 32 bit integer that points to the mentioned adress
#define RCC_APB2ENR  *((volatile uint32_t*)(RCC_base + 0x18))
#define RCC_CFGR *((volatile uint32_t*)(RCC_base + 0x04))
#define RCC_CR *((volatile uint32_t*)(RCC_base + 0x00))


int main(void)
{
	//enabling the HSI on:
	RCC_CR |= (1<<0);

	//Set the PLL source to HSI/2
	RCC_CFGR &= ~(1<<16);

	//PLL multiplication factor
	RCC_CFGR |= (0b0110 << 18); //4*8=32


	//enable the PLL
	RCC_CR |= (1 << 24);

	//set the sysclk source:
	RCC_CFGR &= ~(0b11 << 0); // Clear SW bits (bits 1:0)
	RCC_CFGR |= (0b10 << 0);




	 /*Bits 7:4HPRE: AHB prescaler
	 Set and cleared by software to control the division factor of the AHB clock.
	 0xxx: SYSCLK not divided
	 1000: SYSCLK divided by 2
	 1001: SYSCLK divided by 4
	 1010: SYSCLK divided by 8
	 1011: SYSCLK divided by 16
	 1100: SYSCLK divided by 64
	 1101: SYSCLK divided by 128
	 1110: SYSCLK divided by 256
	 1111: SYSCLK divided by 512*/
	RCC_CFGR |= (0b0000 <<4);

	 /*Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
	 Set and cleared by software to control the division factor of the APB low-speed clock
	(PCLK1).
	 Warning: the software has to set correctly these bits to not exceed 36 MHz on this domain.
	 0xx: HCLK not divided
	 100: HCLK divided by 2
	 101: HCLK divided by 4
	 110: HCLK divided by 8
	 111: HCLK divided by 16*/
	RCC_CFGR |= (0b100 <<8);

	/*Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	 Set and cleared by software to control the division factor of the APB high-speed clock
	(PCLK2).
	 0xx: HCLK not divided
	 100: HCLK divided by 2
	 101: HCLK divided by 4
	 110: HCLK divided by 8
	 111: HCLK divided by 16*/
	RCC_CFGR |= (0b101 <<11);





	// init clock  for GPIO PORT A :
	RCC_APB2ENR |= 1<<2;
	// initiate the GPIO
	GPIO_CRH &=0Xff0fffff;
	GPIO_CRH |=0X00200000;

	while(1)
	{
		GPIOPA_ODR |= 1<<13; //set bit 13
		for( int i=0;i<5000;i++);

		GPIOPA_ODR &= ~(1<<13);
		for(  int i=0;i<5000;i++);
	}


}
