/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103x6.h"
#include "gpio_driver.h"
#include "lcd.h"
#include "keypad.h"
#include "exti_driver.h"
#include "usart_driver.h"


uint8_t ch;

int main(void)
{

	//Enable the clocks
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	UART_Config UartOUScfg;
	UartOUScfg.BaudeRate = UART_BAUDRATE_115200;
	UartOUScfg.HW_Flow_ctrl = UART_HW_FLOW_CTRL_NONE;
	UartOUScfg.IRQ_Enable = UART_IRQ_ENABLE_NONE;
	UartOUScfg.P_IRQ_CALLBACK = NULL;
	UartOUScfg.Parity = UART_Parity_NONE;
	UartOUScfg.Payload_Length = UART_PAYLOAD_LENGTH_8B;
	UartOUScfg.Stopbits = UART_StopBits_1;
	UartOUScfg.USART_MODE = UART_MODE_TX_RX;

	MCAL_UART_INIT(USART1, &UartOUScfg);
	MCAL_UART_GPIO_SET_PINS(USART1);
	while(1)
	{
		MCAL_UART_RECIEVE_DATA(USART1, &ch, enable);
		MCAL_UART_SEND_DATA(USART1, &ch, enable);
	}

}

