/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103x6.h"
#include "gpio_driver.h"
#include "lcd.h"
#include "keypad.h"
#include "exti_driver.h"


unsigned int IRQ_FALG = 0;


void my_delay(int x)
{
	uint32_t i,j;
	for(i=0; i<x ; i++)
	{
		for(j=0; j<255; j++);
	}
}

void EXTI9PB9_CALLBACK(){
	IRQ_FALG = 1;
	LCD_WRITE_STRING("IRQ OF EXTI9 IS OCCURING");
	my_delay(1000);
}

int main(void)
{

	//Enable the clocks
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	LCD_INIT();
	LCD_clear_screen();

	EXTI_PinCnfig_t EXTI_CFG ;
	EXTI_CFG.EXTI_PIN = EXTI9_PB9;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_Rising;
	EXTI_CFG.Ptr_IRQ_CALLBACK = EXTI9PB9_CALLBACK ;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_ENABLE;

	MCAL_EXTI_GPIO_INIT(&EXTI_CFG);

	IRQ_FALG = 1;

	while(1)
	{
		if (IRQ_FALG)
		{
			LCD_clear_screen();
			IRQ_FALG = 0;
		}
	}

}

