/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103x6.h"
#include "STM32F103C6_gpio_driver.h"

void clock_init(){

	//Enable clock for GPIOA
	RCC_GPIOA_CLK_EN();

	////Enable clock for GPIOB
	RCC_GPIOB_CLK_EN();

}

void GPIO_inti(){
	//PORT A pin 1: input float

	GPIO_PinConfig_t PinCfg;

	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA,&PinCfg);



	//PORT B pin 1: output pushpull mode
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10MHZ;
	MCAL_GPIO_Init(GPIOB,&PinCfg);


	//PORT A pin 13: input float
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA,&PinCfg);


	//PORT B pin 13: output pushpull mode
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10MHZ;
	MCAL_GPIO_Init(GPIOB,&PinCfg);

}

void my_wait(int x){
	unsigned int i,j;
	for(i=0; i<x ; i++)
	{
		for(j=0; j<255; j++);
	}
}

int main(void)
{

	clock_init();
	GPIO_inti();

	while(1)
	{	//PA1 connected to external pull-up resistor
		if(MCAL_GPIO_Read_PIN(GPIOA, GPIO_PIN_1) == 0) //Check if Pin A1 is low (button pressed)
		{	// Toggle Pin 1 on Port B
			MCAL_GPIO_Toggle_PIN(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_Read_PIN(GPIOA, GPIO_PIN_1) == 0);//Wait for button release (single press)
		}

		if(MCAL_GPIO_Read_PIN(GPIOA, GPIO_PIN_13) == 1)
		{
			MCAL_GPIO_Toggle_PIN(GPIOB,  GPIO_PIN_13);
		}
		my_wait(1);
	}
}
